Repository Planecode/SimpleComplier, pull requests merged in 2019-10, with the labels that each got.

#11 存储num，id和str并返回地址，增加set存储保留字
  .gitignore
  analysis/lexer.l
Labels: enhancement

#15 实现读取源文件
  analysis/lexer.l
  analysis/parser.y
Labels: enhancement

#20 创建语法树
  .gitignore
  analysis/lexer.l
  analysis/parser.y
  analysis/tree.h
Labels: enhancement

#23 Modify the lexer
  analysis/lexer.l
Labels: enhancement

#26 修复符号表bug
  analysis/lexer.l
  analysis/parser.y
Labels: bug

#28 初始化语法规则
  analysis/lexer.l
  analysis/parser.y
  analysis/tree.h
Labels: enhancement

#30 添加控制语句文法规则
  analysis/lexer.l
  analysis/parser.y
  analysis/tree.h
Labels: enhancement

#34 完善控制语句
  analysis/lexer.l
  analysis/parser.y
Labels: enhancement

#37 调整语法结构
  analysis/lexer.l
  analysis/parser.y
Labels: bug, enhancement

#40 增加if语法
  analysis/parser.y
Labels: enhancement

#44 增加控制语句，添加报错行号
  analysis/lexer.l
  analysis/parser.y
Labels: enhancement
